name: Daily CI Build

on:
  schedule:
    - cron: '23 14 * * 1-5'

defaults:
  run:
    shell: bash -l {0}

jobs:
  get-date:
    runs-on: ubuntu-latest
    steps:
      - name: Add date to github output env
        run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

  test:
    needs: get-date
    uses: arup-group/actions-city-modelling-lab/.github/workflows/python-install-lint-test.yml@repo-name-prefix
    with:
      os: ubuntu-latest
      py3version: "11"
      cache_mamba_env: false
      lint: false
      upload_to_codecov: false
      mamba_env_name: ${{ needs.get-date.outputs.DATE }}
